Inmo/Models/Contrato.cs
using Org.BouncyCastle.Ocsp;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Inmo.Models
{
    public class Contrato : IValidatableObject
    {
        [Key]
        public int? Id { get; set; }


        [Required(ErrorMessage = "Campo requerido")]
       
        public int InmuebleId { get; set; }


        [Required(ErrorMessage = "Campo requerido")]
        
        public int InquilinoId { get; set; }



        [Required(ErrorMessage = "Campo requerido")]
        
        [DataType(DataType.Date)]
        [Display(Name = "Inicio")]
        public DateTime FechaInicio { get; set; }



        [Required(ErrorMessage = "Campo requerido")]    
        [DataType(DataType.Date)]
        [Display(Name = "Fin")]
        public DateTime FechaFin { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [DataType(DataType.Currency, ErrorMessage = "Ingrese un precio válido")]
        [Display(Name = "Precio")]
        [Range(0.01, 100000, ErrorMessage = "El valor debe estar entre .01 y $99999999999")]
        public Decimal Monto { get; set; }


        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(45, ErrorMessage = "Escriba un máximo de 45 caracteres")]
        [Display(Name = "Garante")]
        public string NombreGarante { get; set; }


        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(45, ErrorMessage = "Escriba un máximo de 45 caracteres")]
        [Display(Name = "DNI Garante")]
        public string DniGarante { get; set; }


        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(45, ErrorMessage = "Escriba un máximo de 45 caracteres")]
        [Display(Name = "Telef. Garante")]
        public string TelefonoGarante { get; set; }


        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(45, ErrorMessage = "Escriba un máximo de 45 caracteres")]
        
        [Display(Name = "Mail Garante")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Ingrese un email válido")]
        public string MailGarante { get; set; }


        
        public string? Estado { get; set; }




        
        public Inmueble Inmueble { get; set; }

        
        
        
        public Inquilino Inquilino { get; set; }


        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (FechaInicio > FechaFin)
            {
                yield return new ValidationResult("Existe un error en el ingreso de fechas");
            }

        }
    }
}

Inmo/Controllers/ContratoController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Inmo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MySql.Data.MySqlClient;

namespace Inmo.Controllers
{
    public class ContratoController : BaseController
    {
        private readonly IConfiguration configuration;
        private InmuebleData inmuebleData;
        private InquilinoData inquilinoData;
        private ContratoData contratoData;
        private PagoData pagoData;
        public ContratoController(IConfiguration configuration)
        {
            this.configuration = configuration;
            inmuebleData = new InmuebleData(configuration);
            inquilinoData = new InquilinoData(configuration);
            contratoData = new ContratoData(configuration);
            pagoData = new PagoData(configuration);


        }



        // GET: Contrato
        public ActionResult Index()
        {

            var lista = contratoData.ObtenerTodos();


            return View(lista);
        }

        // GET: Contrato/Details/5
        public ActionResult Details(int id)
        {

            ViewBag.Pagos = pagoData.ObtenerPorContrato(id);
            Contrato c = contratoData.ObtenerPorId(id);

            return View(c);
        }

        public ActionResult Rescindir(int id)
        {
            IList<Pago> pagos = pagoData.ObtenerPorContrato(id);
            ViewBag.Pagos = pagoData.ObtenerPorContrato(id);
            Contrato c = contratoData.ObtenerPorId(id);

            foreach (var item in pagos)
            {
                if (item.FechaVencimiento < DateTime.Now && item.Estado != "pagado")
                {
                    ViewBag.Error = "Posee pagos atrasados, regularice la situacion. No se puede rescindir el contrato";

                    return View("Details",c);
                }
            }
            // calculo de multa

            Double diasIniciales = (c.FechaFin - c.FechaInicio).TotalDays;
            Double diasReales = (DateTime.Now - c.FechaInicio).TotalDays;

            if ((diasIniciales/2)<diasReales)
            {
                ViewBag.Multa = c.Monto * 2;
            }


            c.Estado = "rescindido";
            c.FechaFin = DateTime.Now;
            contratoData.Modificacion(c);

            //foreach (var item in pagos)
            //{
            //    if (item.Estado == "pendiente")
            //    {

            //        item.Estado = "rescindido";
            //        pagoData.Modificacion(item);
            //    }
            //}

            ViewBag.Exito = "El contrato ha sido rescindido";

            


            return View("Details", c);
        }

        // GET: Contrato/Create
        public ActionResult Create()
        {
            var inquilinos = inquilinoData.ObtenerTodos();
            var inmuebles = inmuebleData.ObtenerTodos();

            ViewBag.Inquilinos = inquilinos;
            ViewBag.Inmuebles = inmuebles;
            return View();
        }

        // POST: Contrato/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contrato c)
        {
            int contratoId;
            int i = 1;

            try
            {

                bool validaFecha = inmuebleData.validaFecha(c.FechaInicio.ToShortDateString(), c.FechaFin.ToShortDateString(), c.InmuebleId);

                if (ModelState.IsValid && validaFecha)
                {
                    contratoId = contratoData.Alta(c);
                    IEnumerable<DateTime> lista = MesesEntreDias(c.FechaInicio, c.FechaFin);

                    foreach (var item in lista) {
                        Pago p = new Pago();
                        p.ContratoId = contratoId;
                        p.Estado = "pendiente";
                        p.FechaVencimiento = item.Date.Date;
                        p.Importe = c.Monto;
                        p.Numero = i;
                        i++;
                        pagoData.Alta(p);
                    }
                    return RedirectToAction(nameof(Index));
                }
                var inquilinos = inquilinoData.ObtenerTodos();
                var inmuebles = inmuebleData.ObtenerTodos();
                ViewBag.Inquilinos = inquilinos;
                ViewBag.Inmuebles = inmuebles;
                return View(c);




            }
            catch (MySqlException e)
            {
                return View();
            }
        }

        private static IEnumerable<DateTime> MesesEntreDias(DateTime startDate, DateTime endDate)
        {

            if (endDate < startDate)
                throw new ArgumentException("Error en las fechas ingresadas");

            while (startDate < endDate)
            {
                yield return startDate;
                startDate = startDate.AddMonths(1);
            }

        }

        public ActionResult Renovar(int id) {

            Contrato c = contratoData.ObtenerPorId(id);

            

            return View("Renovar", c);
        }


        // POST: Contrato/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RenovarCrear(Contrato c)
        {
            int contratoId;
            int i = 1;

            try
            {

                bool validaFecha = inmuebleData.validaFecha(c.FechaInicio.ToString("yyyy-MM-dd"), c.FechaFin.ToString("yyyy-MM-dd"), c.InmuebleId);

                if (ModelState.IsValid && validaFecha)
                {
                    contratoId = contratoData.Alta(c);
                    IEnumerable<DateTime> lista = MesesEntreDias(c.FechaInicio, c.FechaFin);

                    foreach (var item in lista)
                    {
                        Pago p = new Pago();
                        p.ContratoId = contratoId;
                        p.Estado = "pendiente";
                        p.FechaVencimiento = item.Date.Date;
                        p.Importe = c.Monto;
                        p.Numero = i;
                        i++;
                        pagoData.Alta(p);
                    }
                    return RedirectToAction(nameof(Index));
                }
                var inquilinos = inquilinoData.ObtenerTodos();
                var inmuebles = inmuebleData.ObtenerTodos();
                ViewBag.Inquilinos = inquilinos;
                ViewBag.Inmuebles = inmuebles;
                ViewBag.Error = "No disponible en las fechas solicitadas. Puede ir a Contrato>Nuevo para consultar fechas";
                return View("Renovar", c);




            }
            catch (MySqlException e)
            {
                return View();
            }
        }


        // GET: Contrato/Edit/5
        public ActionResult Edit(int id)
        {
            Contrato c = contratoData.ObtenerPorId(id);
            return View(c);
        }

        // POST: Contrato/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Contrato c)
        {
            try
            {

                contratoData.Modificacion(c);
                return RedirectToAction(nameof(Index));
            }
            catch (MySqlException e)
            {
                return View();
            }
        }

 
       

        // POST: Contrato/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id, Contrato c)
        {
            try
            {
                contratoData.Baja(id);
                return RedirectToAction(nameof(Index));
            }
            catch (MySqlException e)
            {
                return View();
            }
        }



        public ActionResult BuscaInmuebles(DateTime inicio, DateTime fin)
        {

            IEnumerable<Inmueble> i = inmuebleData.ObtenerTodos();
            
            return PartialView("_InmueblesDisponiblesPartial", i);

        }

        public ActionResult buscar2(DateTime fecha1, DateTime fecha2)
        
        {
            try
            {
                if (fecha1.Date < DateTime.Now.Date)
                {
                    return PartialView("_ErrorPartial", (ViewBag.msj = "La fecha inicio no puede ser inferior a hoy"));
                }
                if (fecha1 > fecha2)
                {
                    return PartialView("_ErrorPartial", (ViewBag.msj = "La fecha inicio no puede ser superior a la fecha de fin"));
                }
                    IEnumerable<Inmueble> i = inmuebleData.disponiblesPorFechas(fecha1, fecha2);
                    return PartialView("_InmueblesPartial", i);
            }
            catch (Exception)
            {
                return PartialView("_ErrorPartial", (ViewBag.msj = "No hay resultados para su busqueda o ha ingresado mal las fechas"));
            }
        }


        public ActionResult vigentes(DateTime inicio, DateTime fin)

        {
            try
            {
                if (inicio > fin)
                {
                    ViewBag.Error = "Error al ingresar las fechas";
                    var lista2 = contratoData.ObtenerTodos();


                    return View(lista2);

                }


                var lista = contratoData.ObtenerPorFechas(inicio, fin);

                return View("Index", lista);
            }
            catch (Exception e)
            {
                return View();
            }
        }
    }


    
}

Inmo/Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Inmo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MySql.Data.MySqlClient;

namespace Inmo.Controllers
{
    public class PagoController : BaseController
    {
        private readonly IConfiguration configuration;
        private PagoData pagoData;
        private ContratoData contratoData;

        public PagoController(IConfiguration configuration)
        {
            this.configuration = configuration;
            pagoData = new PagoData(configuration);
            contratoData = new ContratoData(configuration);

        }
        
        // GET: Pago
        public ActionResult Index()
        {
            var lista = pagoData.ObtenerTodos();
            return View(lista);
        }

        // GET: Pago/Details/5
        public ActionResult Details(int id)
        {
            Pago pago = pagoData.ObtenerPorId(id);
            return View(pago);
        }

        // GET: Pago/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pago/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pago p)
        {
            try
            {
                

                return RedirectToAction(nameof(Index));
            }
            catch(MySqlException ex)
            {
                return View();
            }
        }

        // GET: Pago/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Pago/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // POST: Pago/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Pago/Pagar/5
        public ActionResult Pagar(int id)
        {
            try
            {
                int contrato = (pagoData.ObtenerPorId(id)).ContratoId;

                pagoData.Pagar(id);
                return RedirectToAction("Details", "Contrato", new { id = contrato });
            }
            catch (MySqlException ex)
            {

                throw;
            }
        }
    }
}

Inmo/Views/Contrato/Delete.cshtml
@model Inmo.Models.Contrato

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contrato</h4>
    <hr />
    <dl class="row">
        
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InmuebleId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InmuebleId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InquilinoId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InquilinoId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaFin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaFin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Monto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Monto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreGarante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreGarante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DniGarante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DniGarante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelefonoGarante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelefonoGarante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MailGarante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MailGarante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Inmo/Views/Contrato/Details.cshtml
@model Inmo.Models.Contrato


@{
    ViewData["Title"] = "Detalle Contrato";
}

<div class="row mb-2">
    @if (Model.Estado != "rescindido")
    {
        <a class="btn btn-warning mb-1 ml-2" href="@Url.Action("Rescindir", "Contrato", new { id = @Model.Id })">
            <i class="fi-xnpuxl-home"></i> Rescindir Contrato
        </a>
    }
    else
    {
        <div class="alert alert-default-warning mb-1" role="alert">
            Este contrato ha sido rescindido antes de finalizar
        </div>

    }
</div>




<div class="row">
    <div class="col-md-6 col-lg-6  mx-auto">


        <div class="card card-primary collapsed-card">
            <div class="card-header">
                <h3 class="card-title">Datos de Contrato</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-plus-circle"></i>
                    </button>
                </div>
            </div>

            <!-- aca inicia el form !-->
            <div class="card-body">

                <table class="table stripe">

                    <tbody>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Inmueble.Direccion)
                            </th>
                            <td>
                                @Html.DisplayFor(model => model.Inmueble.Direccion)
                            </td>
                        </tr>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Inquilino.Nombre)
                            </th>
                            <td>
                                @Html.DisplayFor(model => model.Inquilino.Nombre)
                            </td>
                        </tr>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.FechaInicio)
                            </th>
                            <td>
                                @Html.DisplayFor(model => model.FechaInicio)
                            </td>
                        </tr>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.FechaFin)
                            </th>
                            <td>
                                @Html.DisplayFor(model => model.FechaFin)
                            </td>
                        </tr>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Monto)
                            </th>
                            <td>
                                @Html.DisplayFor(model => model.Monto)
                            </td>
                        </tr>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.NombreGarante)
                            </th>
                            <td>
                                @Html.DisplayFor(model => model.NombreGarante)
                            </td>
                        </tr>

                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.DniGarante)
                            </th>
                            <td>
                                @Html.DisplayFor(model => model.DniGarante)
                            </td>
                        </tr>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.TelefonoGarante)
                            </th>
                            <td>
                                @Html.DisplayFor(model => model.TelefonoGarante)
                            </td>
                        </tr>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.MailGarante)
                            </th>
                            <td>
                                @Html.DisplayFor(model => model.MailGarante)
                            </td>
                        </tr>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Estado)
                            </th>
                            <td>
                                @Html.DisplayFor(model => model.Estado)
                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
            <div class="card-footer">
                <div class="form-group">
                    @*@Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" }) |*@
                    <a asp-action="Index" class="btn btn-dark">regresar a la lista</a>
                </div>
            </div>
        </div>
        <!-- /.card-body -->

    </div>
    <div class="col-md-6 col-lg-6  mx-auto">


        <div class="card card-success collapsed-card">
            <div class="card-header">
                <h3 class="card-title">Pagos</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-plus-circle"></i>
                    </button>
                </div>
            </div>

            <!-- aca inicia el form !-->
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>

                            <th>
                                Pago
                            </th>
                            <th>
                                Vencimiento
                            </th>
                            <th>
                                Fecha Pago
                            </th>
                            <th>
                                Importe
                            </th>
                            <th id="estadoPago">
                                Estado
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Pago item in ViewBag.Pagos)
                        {
                            <tr>

                                <td>
                                    @item.Numero
                                </td>
                                <td>
                                    @item.FechaVencimiento.ToShortDateString()
                                </td>
                                <td>
                                    @if (item.FechaPago.ToString() != "01/01/0001 0:00:00")
                                    {

                                        @item.FechaPago.ToShortDateString();
                                    }




                                </td>
                                <td>
                                    @item.Importe
                                </td>
                                <td>
                                    @if (item.FechaVencimiento < DateTime.Now && item.Estado != "pagado")
                                    {
                                        <span class="badge badge-pill badge-danger">Atrasado</span>
                                    }

                                    else
                                    {

                                        @if (item.Estado == "pendiente")
                                        {

                                            <span class="badge badge-pill badge-warning">@item.Estado</span>
                                        }
                                        else
                                        {
                                            <span class="badge badge-pill badge-primary">@item.Estado</span>
                                        }

                                    }


                                </td>


                                <td>
                                    @if (item.Estado != "pagado" && Model.Estado != "rescindido")
                                    {
                                        <a class="btn btn-primary" href="@Url.Action("Pagar", "Pago", new { id = item.Id })">
                                            Pagar

                                        </a>
                                    }



                            </tr>
                        }
                    </tbody>
                </table>



            </div>
            <div class="card-footer">
                <div class="form-group">
                    @*@Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" }) |*@
                    <a asp-action="Index" class="btn btn-dark">regresar a la lista</a>
                </div>
            </div>
        </div>
        <!-- /.card-body -->

    </div>


</div>


@section Scripts {
    <script>
        function borrar(x) {

            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    Swal.fire(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                    alert("/Propietario/Eliminar/" + x);
                    var uri = "/Propietario/Eliminar/" + x
                    window.location = uri;
                }
            }

            )
        }



    </script>


    @if (ViewBag.Multa != null)
    {

        <script>

            Swal.fire(
                'Debe abonar multa',
                '@ViewBag.Multa',
                'error'
            )


        </script>

    }




    
}

Inmo/Views/Contrato/vigentes.cshtml
@{
    ViewData["Title"] = "vigentes";
}

<h1>vigentes</h1>