Inmo/Models/Inquilino.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Inmo.Models
{
    public class Inquilino
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(45, ErrorMessage = "Escriba un máximo de 45 caracteres")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(45, ErrorMessage = "Escriba un máximo de 45 caracteres")]
        public string Apellido { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(45, ErrorMessage = "Escriba un máximo de 45 caracteres")]
        public string Dni { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(45, ErrorMessage = "Escriba un máximo de 45 caracteres")]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(45, ErrorMessage = "Escriba un máximo de 45 caracteres")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(45, ErrorMessage = "Escriba un máximo de 45 caracteres")]
        public string LugarTrabajo { get; set; }
        
        public string Estado { get; set; }

        public List<Contrato> Contrato { get; set; }

    }
}

Inmo/Controllers/InquilinoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Inmo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MySql.Data.MySqlClient;

namespace Inmo.Controllers
{
    public class InquilinoController : BaseController
    {
        private readonly IConfiguration configuration;
        private InmuebleData inmuebleData;
        private InquilinoData inquilinoData;
        private ContratoData contratoData;

        public InquilinoController(IConfiguration configuration)
        {
            this.configuration = configuration;
            inmuebleData = new InmuebleData(configuration);
            inquilinoData = new InquilinoData(configuration);
            contratoData = new ContratoData(configuration);


        }
        


        // GET: Inquilino
        public ActionResult Index()
        {
            var lista = inquilinoData.ObtenerTodos();
            return View(lista);
        }

        // GET: Inquilino/Details/5
        public ActionResult Details(int id)
        {
            Inquilino i = inquilinoData.ObtenerPorId(id);
            return View(i);
        }

        // GET: Inquilino/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Inquilino/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Inquilino i)
        {
            try
            {
                inquilinoData.Alta(i);
                

                return RedirectToAction(nameof(Index));
            }
            catch(MySqlException ex)
            {

                return View();
            }
        }

        // GET: Inquilino/Edit/5
        public ActionResult Edit(int id)
        {
            Inquilino i = inquilinoData.ObtenerPorId(id);
            return View(i);

            
        }

        // POST: Inquilino/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Inquilino i)
        {
            try
            {
                inquilinoData.Modificacion(i);


                return RedirectToAction(nameof(Index));
            }
            catch (MySqlException ex)
            {
                return View();
            }
        }


        // POST: Inquilino/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id, Inquilino i)
        {
            try
            {
                inquilinoData.Baja(id);

                return RedirectToAction(nameof(Index));
            }
            catch (MySqlException ex)
            {
                return View();
            }
        }

        public ActionResult MisContratos(int id)
        {
            try
            {
                ViewBag.Inquilino = inquilinoData.ObtenerPorId(id);
                var lista = contratoData.ObtenerPorInquilino(id);
                return View(lista);
            }
            catch (MySqlException ez)
            {
                return View();
            }
        }
    }
}

Inmo/Views/Inquilino/Create.cshtml
@model Inmo.Models.Inquilino

@{
    ViewData["Title"] = "Nuevo Inquilino";
}




    <div class="row">
        <div class="col-md-12 col-lg-6  mx-auto">
            <div class="card card-primary">
                <div class="card-header">
                    <h6>Crear Nuevo Inquilino</h6>
                </div>
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-12">

                            <div class="card-body">
                                <!--Aca va el form -->
                                <form asp-action="Create">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                                    <div class="form-group">
                                        <label asp-for="Nombre" class="control-label"></label>
                                        <input asp-for="Nombre" class="form-control" />
                                        <span asp-validation-for="Nombre" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Apellido" class="control-label"></label>
                                        <input asp-for="Apellido" class="form-control" />
                                        <span asp-validation-for="Apellido" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Dni" class="control-label"></label>
                                        <input asp-for="Dni" class="form-control" />
                                        <span asp-validation-for="Dni" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Telefono" class="control-label"></label>
                                        <input asp-for="Telefono" class="form-control" />
                                        <span asp-validation-for="Telefono" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Email" class="control-label"></label>
                                        <input asp-for="Email" class="form-control" />
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="LugarTrabajo" class="control-label"></label>
                                        <input asp-for="LugarTrabajo" class="form-control" />
                                        <span asp-validation-for="LugarTrabajo" class="text-danger"></span>
                                    </div>

                                    <div class="form-group">
                                        <input type="submit" value="Guardar" class="btn btn-primary" />
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div>
                        <a asp-action="Index">Regresar a la lista</a>
                    </div>
                </div>
            </div>
        </div>
    </div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Inmo/Views/Inquilino/Delete.cshtml
    <div class="row">
        <div class="col-md-12 col-lg-6  mx-auto">


            <div class="card card-danger">
                <div class="card-header">
                    <h3 class="card-title">Usted va a eliminar un registro</h3>
                </div>

                <!-- aca inicia el form !-->
                <div class="card-body">
                    <form asp-action="Delete">
                        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
                        <a asp-action="Index">Regresar</a>
                    </form>


                </div>
                <!-- /.card-body -->


                <div class="card-footer">
                    
                </div>
                <!-- aca inicia el form !-->
            </div>

        </div>
    </div>
    
    

Inmo/Views/Inquilino/Details.cshtml
@model Inmo.Models.Inquilino

@{
    ViewData["Title"] = "Informacion";
}



    <div class="row">
        <div class="col-md-12 col-lg-6  mx-auto">


            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Propietario</h3>
                </div>

                <!-- aca inicia el form !-->
                <div class="card-body">

                    <div>

                        <dl class="row">


                            <dt class="col-sm-3">
                                @Html.DisplayNameFor(model => model.Nombre)
                            </dt>
                            <dd 9">
                                @Html.DisplayFor(model => model.Nombre)
                            </dd>
                            <dt class="col-sm-3">
                                @Html.DisplayNameFor(model => model.Apellido)
                            </dt>
                            <dd 9">
                                @Html.DisplayFor(model => model.Apellido)
                            </dd>
                            <dt class="col-sm-3">
                                @Html.DisplayNameFor(model => model.Dni)
                            </dt>
                            <dd 9">
                                @Html.DisplayFor(model => model.Dni)
                            </dd>
                            <dt class="col-sm-3">
                                @Html.DisplayNameFor(model => model.Telefono)
                            </dt>
                            <dd 9">
                                @Html.DisplayFor(model => model.Telefono)
                            </dd>
                            <dt class="col-sm-3">
                                @Html.DisplayNameFor(model => model.Email)
                            </dt>
                            <dd 9">
                                @Html.DisplayFor(model => model.Email)
                            </dd>
                            <dt class="col-sm-3">
                                @Html.DisplayNameFor(model => model.LugarTrabajo)
                            </dt>
                            <dd 9">
                                @Html.DisplayFor(model => model.LugarTrabajo)
                            </dd>
                            <dt class="col-sm-3">
                                @Html.DisplayNameFor(model => model.Estado)
                            </dt>
                            <dd 9">
                                @Html.DisplayFor(model => model.Estado)
                            </dd>
                        </dl>

                    </div>

                </div>
                <!-- /.card-body -->


                <div class="card-footer">
                    <div class="form-group">
                        @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" }) |
                        <a asp-action="Index" class="btn btn-dark">regresar a la lista</a>
                    </div>
                </div>
                <!-- aca inicia el form !-->
            </div>

        </div>
    </div>

Inmo/Views/Inquilino/Edit.cshtml
@model Inmo.Models.Inquilino

@{
    ViewData["Title"] = "Edit";
}



<div class="row">
    <div class="col-md-12 col-lg-6  mx-auto">
        <div class="card card-primary">
            <div class="card-header">
                <h6>Editar Inquilino</h6>
            </div>
            <div class="card-body">

                <div class="row">
                    <div class="col-md-12">

                        <div class="card-body">


                            <form asp-action="Edit">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group" hidden>
                                    <label asp-for="Id" class="control-label"></label>
                                    <input asp-for="Id" class="form-control" />
                                    <span asp-validation-for="Id" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Nombre" class="control-label"></label>
                                    <input asp-for="Nombre" class="form-control" />
                                    <span asp-validation-for="Nombre" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Apellido" class="control-label"></label>
                                    <input asp-for="Apellido" class="form-control" />
                                    <span asp-validation-for="Apellido" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Dni" class="control-label"></label>
                                    <input asp-for="Dni" class="form-control" />
                                    <span asp-validation-for="Dni" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Telefono" class="control-label"></label>
                                    <input asp-for="Telefono" class="form-control" />
                                    <span asp-validation-for="Telefono" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Email" class="control-label"></label>
                                    <input asp-for="Email" class="form-control" />
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="LugarTrabajo" class="control-label"></label>
                                    <input asp-for="LugarTrabajo" class="form-control" />
                                    <span asp-validation-for="LugarTrabajo" class="text-danger"></span>
                                </div>
                                <div class="form-group" hidden>
                                    <label asp-for="Estado" class="control-label"></label>
                                    <input asp-for="Estado" class="form-control" />
                                    <span asp-validation-for="Estado" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Guardar" class="btn btn-primary" />
                                </div>
                            </form>

                        </div>
                </div>
            </div>
            <div class="card-footer">
                <div>
                    <a asp-action="Index">Regresar a la lista</a>
                </div>
            </div>
        </div>
    </div>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Inmo/Views/Inquilino/Index.cshtml
@model IEnumerable<Inmo.Models.Inquilino>

@{
    ViewData["Title"] = "Inquilinos";
}



    <div class="card card-primary">
        <div class="card-header">
            <a asp-action="Create" class="btn btn-secondary float-left">
                <i class="fas fa-plus-circle">
                </i> Agregar Inquilino
            </a>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body">

            <table id="tabla" class="table table-bordered table-striped dataTable" role="grid">
                <thead>
                    <tr>

                        <th>
                            @Html.DisplayNameFor(model => model.Nombre)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Apellido)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Dni)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Telefono)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>

                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>

                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Apellido)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Dni)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Telefono)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>

                            <td>
                                <div class="btn-group-sm">
                                    <a class="btn btn-primary" href="@Url.Action("Details", "Inquilino", new { id = item.Id })">
                                        <i class="fas fa-eye">
                                        </i>


                                    </a>
                                    <a class="btn btn-info" href="@Url.Action("Edit", "Inquilino", new { id = item.Id })">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                    </a>
                                    <a class="btn btn-success" href="@Url.Action("Miscontratos", "Inquilino", new { id = item.Id })">
                                        <i class="fas fa-home"></i>
                                    </a>

                                    <a class="btn btn-danger" href="@Url.Action("Delete", "Inquilino", new { id = item.Id })">
                                        <i class="fas fa-trash">
                                        </i>

                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Nombre)</th>
                        <th>@Html.DisplayNameFor(model => model.Apellido)</th>
                        <th>@Html.DisplayNameFor(model => model.Dni)</th>
                        <th>@Html.DisplayNameFor(model => model.Telefono)</th>
                        <th>@Html.DisplayNameFor(model => model.Email)</th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="card-footer">
            
        </div>
    </div>

@section Scripts {



}

Inmo/Views/Inquilino/MisContratos.cshtml
@model IEnumerable<Inmo.Models.Contrato>

@{
    ViewData["Title"] = "Mis Contratos";
}


<div class="card card-primary">
    <div class="card-header">
        <a asp-action="Create" class="btn btn-secondary float-left">
            <i class="fas fa-plus-circle">
            </i> Agregar Contrato
        </a>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fas fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="card-body">
        <table id="tabla" class="table table-bordered table-striped dataTable" role="grid">
            <thead>
                <tr>

                    <th>@Html.DisplayNameFor(model => model.FechaInicio)
                    </th>
                    <th>@Html.DisplayNameFor(model => model.FechaFin)
                    </th>
                    <th>@Html.DisplayNameFor(model => model.Monto)
                    </th>
                    <th>@Html.DisplayNameFor(model => model.NombreGarante)
                    </th>
                    <th>@Html.DisplayNameFor(model => model.DniGarante)
                    </th>
                    <th>@Html.DisplayNameFor(model => model.TelefonoGarante)
                    </th>
                    <th>@Html.DisplayNameFor(model => model.MailGarante)
                    </th>
                    <th>@Html.DisplayNameFor(model => model.Estado)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.FechaInicio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaFin)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Monto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NombreGarante)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DniGarante)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TelefonoGarante)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MailGarante)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Estado)
                        </td>
                        <td>
                            <a class="btn btn-primary" href="@Url.Action("Details", "Contrato", new { id = item.Id })">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a class="btn btn-info" href="@Url.Action("Renovar", "Contrato", new { id = item.Id })">
                                <i class="fas fa-redo-alt"></i>
                            </a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
    <div class="card-footer">
        
    </div>
</div>
@section Scripts {

    <script>


    </script>


}